"""empty message

Revision ID: 47d75ce4ad61
Revises: 
Create Date: 2023-02-02 16:35:04.920554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d75ce4ad61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Routine',
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('routine_name', sa.String(length=20), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('routine_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('pw', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('animals',
    sa.Column('animal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('animal_name', sa.String(length=10), nullable=False),
    sa.Column('bday', sa.String(length=10), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('neutered', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('animal_id'),
    sa.UniqueConstraint('animal_id')
    )
    op.create_table('checklist_default',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currdate', sa.DateTime(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('food', sa.String(length=10), nullable=True),
    sa.Column('bowels', sa.String(length=10), nullable=True),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.animal_id'], ),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('currdate'),
    sa.UniqueConstraint('index')
    )
    op.create_table('checklist_routine',
    sa.Column('index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currdate', sa.DateTime(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.animal_id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['Routine.routine_id'], ),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('currdate'),
    sa.UniqueConstraint('index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_routine')
    op.drop_table('checklist_default')
    op.drop_table('animals')
    op.drop_table('user')
    op.drop_table('Routine')
    # ### end Alembic commands ###
